export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_MIGRATION = "CREATE_MIGRATION";
export const LOAD_MIGRATIONS_SUCCESS = "LOAD_MIGRATIONS_SUCCESS";
export const CREATE_MIGRATION_SUCCESS = "CREATE_MIGRATION_SUCCESS";
export const UPDATE_MIGRATION_SUCCESS = "UPDATE_MIGRATION_SUCCESS";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_MEMBERS_SUCCESS = "LOAD_MEMBERS_SUCCESS";
