/* App - Member Actions */
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const RESET_MEMBER_SUCCESS = "RESET_MEMBER_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";

/* App - Migration Actions */
export const CREATE_MIGRATION_SUCCESS = "CREATE_MIGRATION_SUCCESS";
export const DELETE_MIGRATION_SUCCESS = "DELETE_MIGRATION_SUCCESS";
export const GET_MIGRATION_SUCCESS = "GET_MIGRATION_SUCCESS";
export const GET_MIGRATIONS_SUCCESS = "GET_MIGRATIONS_SUCCESS";
export const RESET_MIGRATION_SUCCESS = "RESET_MIGRATION_SUCCESS";
export const UPDATE_MIGRATION_SUCCESS = "UPDATE_MIGRATION_SUCCESS";

/* App - Task Actions */
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const RESET_TASK_SUCCESS = "RESET_TASK_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

/* App - Stage Actions */


export const GET_STAGES_SUCCESS = "GET_STAGES_SUCCESS";
export const RESET_STAGES_SUCCESS = "RESET_STAGES_SUCCESS";
export const UPDATE_STAGES_SUCCESS = "UPDATE_STAGES_SUCCESS";

/* App - Toggle Actions */
export const TOGGLE_MEMBER_MODAL = "TOGGLE_MEMBER_MODAL";
export const TOGGLE_MIGRATION_MODAL = "TOGGLE_MIGRATION_MODAL";
export const TOGGLE_STAGE_MODAL = "TOGGLE_STAGE_MODAL";
export const TOGGLE_TASK_MODAL = "TOGGLE_TASK_MODAL";

