/* App - Author Actions */
// export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
// export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
// export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
// export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
// export const RESET_AUTHOR_SUCCESS = "RESET_AUTHOR_SUCCESS";
// export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";

/* App - Course Actions */
// export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
// export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
// export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
// export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
// export const RESET_COURSE_SUCCESS = "RESET_COURSE_SUCCESS";
// export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

/* App - Member Actions */
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const RESET_MEMBER_SUCCESS = "RESET_MEMBER_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";

/* App - Migration Actions */
export const CREATE_MIGRATION_SUCCESS = "CREATE_MIGRATION_SUCCESS";
export const DELETE_MIGRATION_SUCCESS = "DELETE_MIGRATION_SUCCESS";
export const GET_MIGRATION_SUCCESS = "GET_MIGRATION_SUCCESS";
export const GET_MIGRATIONS_SUCCESS = "GET_MIGRATIONS_SUCCESS";
export const RESET_MIGRATION_SUCCESS = "RESET_MIGRATION_SUCCESS";
export const UPDATE_MIGRATION_SUCCESS = "UPDATE_MIGRATION_SUCCESS";

/* App - Toggle Actions */
export const TOGGLE_MEMBER_MODAL = "TOGGLE_MEMBER_MODAL";
export const TOGGLE_MIGRATION_MODAL = "TOGGLE_MIGRATION_MODAL";
export const TOGGLE_STAGE_MODAL = "TOGGLE_STAGE_MODAL";
export const TOGGLE_TASK_MODAL = "TOGGLE_TASK_MODAL";
