const courses = [
  {
    id: 1,
    title: "Securing React Apps with Auth0",
    slug: "react-auth0-authentication-security",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 2,
    title: "React: The Big Picture",
    slug: "react-big-picture",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 3,
    title: "Creating Reusable React Components",
    slug: "react-creating-reusable-components",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 4,
    title: "Building a JavaScript Development Environment",
    slug: "javascript-development-environment",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 5,
    title: "Building Applications with React and Redux",
    slug: "react-redux-react-router-es6",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 6,
    title: "Building Applications in React and Flux",
    slug: "react-flux-building-applications",
    authorId: 1,
    category: "JavaScript",
  },
  {
    id: 7,
    title: "Clean Code: Writing Code for Humans",
    slug: "writing-clean-code-humans",
    authorId: 1,
    category: "Software Practices",
  },
  {
    id: 8,
    title: "Architecting Applications for the Real World",
    slug: "architecting-applications-dotnet",
    authorId: 1,
    category: "Software Architecture",
  },
  {
    id: 9,
    title: "Becoming an Outlier: Reprogramming the Developer Mind",
    slug: "career-reboot-for-developer-mind",
    authorId: 1,
    category: "Career",
  },
  {
    id: 10,
    title: "Web Component Fundamentals",
    slug: "web-components-shadow-dom",
    authorId: 1,
    category: "HTML5",
  },
];

const authors = [
  { id: 1, name: "Cory House" },
  { id: 2, name: "Scott Allen" },
  { id: 3, name: "Dan Wahlin" },
];

const newCourse = {
  id: null,
  title: "",
  authorId: null,
  category: "",
};

const members = [
  {
    id: 1,
    name: "Shannon",
    sname: "S Palmer",
    alias: "Vision",
    pic: "/src/images/Vision.svg",
    focus: false,
  },
  {
    id: 2,
    name: "Mike",
    sname: "M Randall",
    alias: "Hulk",
    pic: "/src/images/Hulk.svg",
    focus: false,
  },
  {
    id: 3,
    name: "Jean",
    sname: "J Lamboy",
    alias: "Jean",
    pic: "/src/images/Jean.svg",
    focus: false,
  },
  {
    id: 4,
    name: "Geraldine",
    sname: "G Montgomery",
    alias: "Storm",
    pic: "/src/images/Storm.svg",
    focus: false,
  },
  {
    id: 5,
    name: "Justin",
    sname: "J Barnett",
    alias: "Deadpool",
    pic: "/src/images/Deadpool.svg",
    focus: false,
  },
  {
    id: 6,
    name: "Christian",
    sname: "C Marzan",
    alias: "Sunspot",
    pic: "/src/images/Sunspot.svg",
    focus: false,
  },
  {
    id: 7,
    name: "Lee",
    sname: "L Oxley",
    alias: "Strange",
    pic: "/src/images/Strange.svg",
    focus: false,
  },
];

const migrations = [
  {
    migration_id: 1,
    migration_owner: 2,
    migration_type: "PaaS",
    os: "nothing",
    app_name: "MOBB",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "In-Progress",
    S2_T3: "Stuck",
    S2_T4: "In-Progress",
  },
  {
    migration_id: 2,
    migration_owner: 2,
    migration_type: "PaaS",
    os: "nothing",
    app_name: "W3.SPA",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "Stuck",
  },
  {
    migration_id: 3,
    migration_owner: 2,
    migration_type: "IaaS",
    os: "Linux",
    app_name: "SooWebCams",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "Complete",
    S3_T2: "In-Progress",
    S3_T3: "In-Progress",
  },
  {
    migration_id: 4,
    migration_owner: 1,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "WC.LRL",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "Not-Started",
    S1_T4: "Not-Started",
    S1_T5: "Not-Started",
    S1_T6: "Not-Started",
    S1_T7: "Not-Started",
    S1_T8: "Not-Started",
    S1_T9: "Not-Started",
    S1_T10: "Not-Started",
    S1_T11: "Not-Started",
    S2_T1: "Not-Started",
    S2_T2: "Not-Started",
    S2_T3: "Not-Started",
    S2_T4: "Not-Started",
    S2_T5: "Not-Started",
    S3_T1: "Not-Started",
    S3_T2: "Not-Started",
    S3_T3: "Not-Started",
    S3_T4: "Not-Started",
    S3_T5: "Not-Started",
    S3_T6: "Not-Started",
    S3_T7: "Not-Started",
    S3_T8: "Not-Started",
    S3_T9: "Not-Started",
    S3_T10: "Not-Started",
    S3_T11: "Not-Started",
  },
  {
    migration_id: 5,
    migration_owner: 3,
    migration_type: "IaaS",
    os: "Linux",
    app_name: "ERD.RSM",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "In-Progress",
    S1_T6: "In-Progress",
  },
  {
    migration_id: 6,
    migration_owner: 3,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "ERD.CIRP",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "In-Progress",
    S3_T2: "Stuck",
    S3_T3: "Stuck",
    S3_T4: "In-Progress",
  },
  {
    migration_id: 7,
    migration_owner: 5,
    migration_type: "PaaS",
    os: "nothing",
    app_name: "LRP.GEO",
    S1_T1: "In-Progress",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "In-Progress",
    S1_T6: "In-Progress",
    S1_T7: "Complete",
  },
  {
    migration_id: 8,
    migration_owner: 5,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "G6.EFT",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "Complete",
    S3_T2: "Complete",
    S3_T3: "Complete",
    S3_T4: "Complete",
    S3_T5: "Complete",
    S3_T6: "Complete",
    S3_T7: "Complete",
    S3_T8: "Complete",
    S3_T9: "Complete",
    S3_T10: "Complete",
    S3_T11: "Complete",
  },
];

const migration_stages = [
  {
    stage_id: 1,
    stage: "Engage customer",
  },
  {
    stage_id: 2,
    stage: "Request approval",
  },
  {
    stage_id: 3,
    stage: "Request resources",
  },
  {
    stage_id: 4,
    stage: "Configure resources",
  },
  {
    stage_id: 5,
    stage: "Testing",
  },
  {
    stage_id: 6,
    stage: "Cutover",
  },
  {
    stage_id: 7,
    stage: "Closeout",
  },
];

const migration_tasks = [
  {
    task_id: 1,
    stage: 1,
    task: "Create SSI ticket to track migration",
  },
  {
    task_id: 2,
    stage: 1,
    task: "Kick off with customer",
  },
  {
    task_id: 3,
    stage: 1,
    task: "Complete the Application Service Document (ASD)",
  },
  {
    task_id: 4,
    stage: 1,
    task: "Request Public Affairs Office (PAO) approval email",
  },
  {
    task_id: 5,
    stage: 1,
    task:
      "Request Impact Level Assessment and Information Survey Type be completed",
  },
  {
    task_id: 6,
    stage: 1,
    task: "Request 508 scan compliance in a work order",
  },
  {
    task_id: 7,
    stage: 1,
    task: "Request HPFortify scan on site",
  },
  {
    task_id: 8,
    stage: 1,
    task: "Create diagram",
  },
  {
    task_id: 9,
    stage: 1,
    task:
      "Fill out the (VM request - IaaS) or (Webapp request - PaaS) form based on your project type",
  },
  {
    task_id: 10,
    stage: 2,
    task: "Request Cloud Service Program Management Office (CSPMO) approval",
  },
  {
    task_id: 11,
    stage: 2,
    task: "Create work order",
  },
  {
    task_id: 12,
    stage: 2,
    task: "Schedule meeting with engineering",
  },
  {
    task_id: 13,
    stage: 2,
    task: "Include diagram and request worksheet",
  },
  {
    task_id: 14,
    stage: 3,
    task: "Request resources provisioned ('VM', App server, database, webapp)",
  },
  {
    task_id: 15,
    stage: 3,
    task: "Verify Windows/RHEL VM configuration",
  },
  {
    task_id: 16,
    stage: 3,
    task: "Confirm server in correct vnet/subnet",
  },
  {
    task_id: 17,
    stage: 3,
    task: "Confirm tags are accurate",
  },
  {
    task_id: 18,
    stage: 3,
    task: "Confirm/Request our group (- ????) is added to access server",
  },
  {
    task_id: 19,
    stage: 3,
    task: "Confirm/Test login access to the server using RDP/SSH",
  },
  {
    task_id: 20,
    stage: 3,
    task: "Confirm/Test access to server using SFTP",
  },
  {
    task_id: 21,
    stage: 3,
    task: "Confirm that app storage is mounted",
  },
  {
    task_id: 22,
    stage: 3,
    task: "Update ASD with server information",
  },
  {
    task_id: 23,
    stage: 3,
    task: "Update Azure IL4 server spreadsheet",
  },
  {
    task_id: 24,
    stage: 3,
    task: "Request HPFortify scan on new server",
  },
  {
    task_id: 25,
    stage: 4,
    task: "Configure database",
  },
  {
    task_id: 26,
    stage: 4,
    task: "Configure staging server",
  },
  {
    task_id: 27,
    stage: 4,
    task: "Configure website",
  },
  {
    task_id: 28,
    stage: 4,
    task: "Confirm AD Group or LDAP Role is created (name of group or role)",
  },
  {
    task_id: 29,
    stage: 4,
    task: "Create IIS config doc",
  },
  {
    task_id: 30,
    stage: 4,
    task: "Configure app server",
  },
  {
    task_id: 31,
    stage: 4,
    task: "Update ASD with applicable information",
  },
  {
    task_id: 32,
    stage: 5,
    task: "Request customer test app/site",
  },
  {
    task_id: 32,
    stage: 5,
    task: "Notify customer that app/site configured",
    notes:
      "Isn't the site already configured since in previous we requested they test?",
  },
  {
    task_id: 33,
    stage: 5,
    task: "Verify that customer can access the site",
    notes: "How is test app/site different from access site?",
  },
  {
    task_id: 34,
    stage: 5,
    task: "Verify that customer can WinSCP to server and upload files",
  },
  {
    task_id: 35,
    stage: 5,
    task: "Verify that automation of file transer is working for customer",
    notes: "Does this apply to only PaaS with it's staging?",
  },
  {
    task_id: 36,
    stage: 6,
    task: "DNS update",
  },
  {
    task_id: 37,
    stage: 7,
    task: "Email service owner and operations team",
  },
  {
    task_id: 38,
    stage: 7,
    task: "Update the all sites (Core) list",
  },
];

const migration_types = [
  { id: 1, migration_type: "PaaS" },
  { id: 2, migration_type: "IaaS" },
];

const newMigration = {
  migration_id: null,
  migration_ownerId: null,
  migration_typeId: null,
  os: null,
  app_name: null,
  migration_status: "Not-Started",
};

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  newCourse,
  newMigration,
  courses,
  authors,
  members,
  migrations,
  migration_tasks,
  migration_stages,
  migration_types,
};
