const members = [
  {
    id: 1,
    name: "Shannon",
    sname: "S Palmer",
    alias: "Vision",
    pic: "/src/images/Vision.svg",
    focus: false,
  },
  {
    id: 2,
    name: "Mike",
    sname: "M Randall",
    alias: "Hulk",
    pic: "/src/images/Hulk.svg",
    focus: false,
  },
  {
    id: 3,
    name: "Jean",
    sname: "J Lamboy",
    alias: "Jean",
    pic: "/src/images/Jean.svg",
    focus: false,
  },
  {
    id: 4,
    name: "Geraldine",
    sname: "G Montgomery",
    alias: "Storm",
    pic: "/src/images/Storm.svg",
    focus: false,
  },
  {
    id: 5,
    name: "Justin",
    sname: "J Barnett",
    alias: "Deadpool",
    pic: "/src/images/Deadpool.svg",
    focus: false,
  },
  {
    id: 6,
    name: "Christian",
    sname: "C Marzan",
    alias: "Sunspot",
    pic: "/src/images/Sunspot.svg",
    focus: false,
  },
  {
    id: 7,
    name: "Lee",
    sname: "L Oxley",
    alias: "Strange",
    pic: "/src/images/Strange.svg",
    focus: false,
  },
];

const migrations = [
  {
    id: 1,
    migration_ownerId: 2,
    migration_type: "PaaS",
    os: null,
    app_name: "MOBB",
    status: "Stuck",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "In-Progress",
    S2_T3: "Stuck",
    S2_T4: "In-Progress",
  },
  {
    id: 2,
    migration_ownerId: 2,
    migration_type: "PaaS",
    os: null,
    app_name: "W3.SPA",
    status: "Stuck",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "Stuck",
  },
  {
    id: 3,
    migration_ownerId: 2,
    migration_type: "IaaS",
    os: "Linux",
    app_name: "SOOWEBCAMS",
    status: "In-Progress",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "Complete",
    S3_T2: "In-Progress",
    S3_T3: "In-Progress",
  },
  {
    id: 4,
    migration_ownerId: 1,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "WC.LRL",
    status: "In-Progress",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "Not-Started",
    S1_T4: "Not-Started",
    S1_T5: "Not-Started",
    S1_T6: "Not-Started",
    S1_T7: "Not-Started",
    S1_T8: "Not-Started",
    S1_T9: "Not-Started",
    S1_T10: "Not-Started",
    S1_T11: "Not-Started",
    S2_T1: "Not-Started",
    S2_T2: "Not-Started",
    S2_T3: "Not-Started",
    S2_T4: "Not-Started",
    S2_T5: "Not-Started",
    S3_T1: "Not-Started",
    S3_T2: "Not-Started",
    S3_T3: "Not-Started",
    S3_T4: "Not-Started",
    S3_T5: "Not-Started",
    S3_T6: "Not-Started",
    S3_T7: "Not-Started",
    S3_T8: "Not-Started",
    S3_T9: "Not-Started",
    S3_T10: "Not-Started",
    S3_T11: "Not-Started",
  },
  {
    id: 5,
    migration_ownerId: 4,
    migration_type: "IaaS",
    os: "Linux",
    app_name: "ERD.RSM",
    status: "In-Progress",
    S1_T1: "Complete",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "In-Progress",
    S1_T6: "In-Progress",
  },
  {
    id: 6,
    migration_ownerId: 3,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "ERD.CIRP",
    status: "Stuck",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "In-Progress",
    S3_T2: "Stuck",
    S3_T3: "Stuck",
    S3_T4: "In-Progress",
  },
  {
    id: 7,
    migration_ownerId: 5,
    migration_type: "PaaS",
    os: null,
    app_name: "LRP.GEO",
    status: "In-Progress",
    S1_T1: "In-Progress",
    S1_T2: "In-Progress",
    S1_T3: "In-Progress",
    S1_T4: "In-Progress",
    S1_T5: "In-Progress",
    S1_T6: "In-Progress",
    S1_T7: "Complete",
  },
  {
    id: 8,
    migration_ownerId: 5,
    migration_type: "IaaS",
    os: "Windows",
    app_name: "G6.EFT",
    status: "Complete",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "Complete",
    S2_T3: "Complete",
    S2_T4: "Complete",
    S2_T5: "Complete",
    S3_T1: "Complete",
    S3_T2: "Complete",
    S3_T3: "Complete",
    S3_T4: "Complete",
    S3_T5: "Complete",
    S3_T6: "Complete",
    S3_T7: "Complete",
    S3_T8: "Complete",
    S3_T9: "Complete",
    S3_T10: "Complete",
    S3_T11: "Complete",
  },
  {
    id: 9,
    migration_ownerId: 4,
    migration_type: "PaaS",
    os: null,
    app_name: "MOBBEY",
    status: "Stuck",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "In-Progress",
    S2_T3: "Stuck",
    S2_T4: "In-Progress",
  },
  {
    id: 10,
    migration_ownerId: 2,
    migration_type: "PaaS",
    os: null,
    app_name: "CRABB",
    status: "In-Progress",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "In-Progress",
    S2_T3: "In-Progress",
    S2_T4: "In-Progress",
  },
  {
    id: 11,
    migration_ownerId: 6,
    migration_type: "IaaS",
    os: null,
    app_name: "SIMPLE",
    status: "In-Progress",
    S1_T1: "Complete",
    S1_T2: "Complete",
    S1_T3: "Complete",
    S1_T4: "Complete",
    S1_T5: "Complete",
    S1_T6: "Complete",
    S1_T7: "Complete",
    S1_T8: "Complete",
    S1_T9: "Complete",
    S1_T10: "Complete",
    S1_T11: "Complete",
    S2_T1: "Complete",
    S2_T2: "In-Progress",
    S2_T3: "In-Progress",
    S2_T4: "In-Progress",
  },
];

const migration_stages = [
  {
    id: 1,
    stage: "Engage customer",
  },
  {
    id: 2,
    stage: "Request approval",
  },
  {
    id: 3,
    stage: "Request resources",
  },
  {
    id: 4,
    stage: "Configure resources",
  },
  {
    id: 5,
    stage: "Testing",
  },
  {
    id: 6,
    stage: "Cutover",
  },
  {
    id: 7,
    stage: "Closeout",
  },
];

const migration_tasks = [
  {
    id: 1,
    stageId: 1,
    task: "Create SSI ticket to track migration",
  },
  {
    id: 2,
    stageId: 1,
    task: "Kick off with customer",
  },
  {
    id: 3,
    stageId: 1,
    task: "Complete the Application Service Document (ASD)",
  },
  {
    id: 4,
    stageId: 1,
    task: "Request Public Affairs Office (PAO) approval email",
  },
  {
    id: 5,
    stageId: 1,
    task:
      "Request Impact Level Assessment and Information Survey Type be completed",
  },
  {
    id: 6,
    stageId: 1,
    task: "Request 508 scan compliance in a work order",
  },
  {
    id: 7,
    stageId: 1,
    task: "Request HPFortify scan on site",
  },
  {
    id: 8,
    stageId: 1,
    task: "Create diagram",
  },
  {
    id: 9,
    stageId: 1,
    task:
      "Fill out the (VM request - IaaS) or (Webapp request - PaaS) form based on your project type",
  },
  {
    id: 10,
    stageId: 2,
    task: "Request Cloud Service Program Management Office (CSPMO) approval",
  },
  {
    id: 11,
    stageId: 2,
    task: "Create work order",
  },
  {
    id: 12,
    stageId: 2,
    task: "Schedule meeting with engineering",
  },
  {
    id: 13,
    stageId: 2,
    task: "Include diagram and request worksheet",
  },
  {
    id: 14,
    stageId: 3,
    task: "Request resources provisioned ('VM', App server, database, webapp)",
  },
  {
    id: 15,
    stageId: 3,
    task: "Verify Windows/RHEL VM configuration",
  },
  {
    id: 16,
    stageId: 3,
    task: "Confirm server in correct vnet/subnet",
  },
  {
    id: 17,
    stageId: 3,
    task: "Confirm tags are accurate",
  },
  {
    id: 18,
    stageId: 3,
    task: "Confirm/Request our group (- ????) is added to access server",
  },
  {
    id: 19,
    stageId: 3,
    task: "Confirm/Test login access to the server using RDP/SSH",
  },
  {
    id: 20,
    stageId: 3,
    task: "Confirm/Test access to server using SFTP",
  },
  {
    id: 21,
    stageId: 3,
    task: "Confirm that app storage is mounted",
  },
  {
    id: 22,
    stageId: 3,
    task: "Update ASD with server information",
  },
  {
    id: 23,
    stageId: 3,
    task: "Update Azure IL4 server spreadsheet",
  },
  {
    id: 24,
    stageId: 3,
    task: "Request HPFortify scan on new server",
  },
  {
    id: 25,
    stageId: 4,
    task: "Configure database",
  },
  {
    id: 26,
    stageId: 4,
    task: "Configure staging server",
  },
  {
    id: 27,
    stageId: 4,
    task: "Configure website",
  },
  {
    id: 28,
    stageId: 4,
    task: "Confirm AD Group or LDAP Role is created (name of group or role)",
  },
  {
    id: 29,
    stageId: 4,
    task: "Create IIS config doc",
  },
  {
    id: 30,
    stageId: 4,
    task: "Configure app server",
  },
  {
    id: 31,
    stageId: 4,
    task: "Update ASD with applicable information",
  },
  {
    id: 32,
    stageId: 5,
    task: "Request customer test app/site",
  },
  {
    id: 32,
    stageId: 5,
    task: "Notify customer that app/site configured",
    notes:
      "Isn't the site already configured since in previous we requested they test?",
  },
  {
    id: 33,
    stageId: 5,
    task: "Verify that customer can access the site",
    notes: "How is test app/site different from access site?",
  },
  {
    id: 34,
    stageId: 5,
    task: "Verify that customer can WinSCP to server and upload files",
  },
  {
    id: 35,
    stageId: 5,
    task: "Verify that automation of file transer is working for customer",
    notes: "Does this apply to only PaaS with it's staging?",
  },
  {
    id: 36,
    stageId: 6,
    task: "DNS update",
  },
  {
    id: 37,
    stageId: 7,
    task: "Email service owner and operations team",
  },
  {
    id: 38,
    stageId: 7,
    task: "Update the all sites (Core) list",
  },
];

const operating_systems = [
  { id: 1, os: "Windows" },
  { id: 2, os: "Linux" },
];

const migration_types = [
  { id: 1, migration_type: "PaaS" },
  { id: 2, migration_type: "IaaS" },
];

const newMigration = {
  id: null,
  ownerId: null,
  migrationTypeId: null,
  os: null,
  app_name: "",
  status: "Not-Started",
  S1_T1: "Not-Started",
  S1_T2: "Not-Started",
  S1_T3: "Not-Started",
  S1_T4: "Not-Started",
  S1_T5: "Not-Started",
  S1_T6: "Not-Started",
  S1_T7: "Not-Started",
  S1_T8: "Not-Started",
  S1_T9: "Not-Started",
  S1_T10: "Not-Started",
  S1_T11: "Not-Started",
  S2_T1: "Not-Started",
  S2_T2: "Not-Started",
  S2_T3: "Not-Started",
  S2_T4: "Not-Started",
  S2_T5: "Not-Started",
  S3_T1: "Not-Started",
  S3_T2: "Not-Started",
  S3_T3: "Not-Started",
  S3_T4: "Not-Started",
  S3_T5: "Not-Started",
  S3_T6: "Not-Started",
  S3_T7: "Not-Started",
  S3_T8: "Not-Started",
  S3_T9: "Not-Started",
  S3_T10: "Not-Started",
  S3_T11: "Not-Started",
};

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  newMigration,
  members,
  migrations,
  migration_tasks,
  migration_stages,
  migration_types,
  operating_systems,
};
